version: '3.1'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: ./node
    container_name: node
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s sh -c "npm install && npm run start"
    networks:
      - node-network
    depends_on:
      - mysql
  mysql:
    build: ./data
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    tty: true
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network
    ports:
      - "3306:3306"

networks:
  node-network:
    driver: bridge
